[general]
import = [
    #"~/.config/alacritty/themes/themes/gruvbox_dark.toml"
    "~/.config/alacritty/themes/themes/dracula_plus.toml"
    #~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
    #"~/.config/alacritty/themes/themes/tokyo-night.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dimensions.columns = 120
dimensions.lines = 35
padding.x = 10
padding.y = 10
dynamic_padding = true
opacity = 0.8
blur = true
option_as_alt = "Both"

[font]
normal.family = "SauceCodePro NFM"
normal.style = "Regular"
size = 18

[cursor]
style.shape = "Beam"
style.blinking = "On" 
blink_timeout = 0

