#! /usr/bin/env sh
# this is a example of .lessfilter, you can change it
mime=$(file -bL --mime-type "$1")
category=${mime%%/*}
kind=${mime##*/}
if [ -d "$1" ]; then
  eza -ghlmF --color=always --color-scale=all --color-scale-mode=gradient --icons=always --hyperlink --no-time "$1"
elif [ "$category" = image ]; then
  if [ "$LC_TERMINAL" = iTerm2 ]; then
    imgcat -r -W 50% -H 50% "$1"
  else
    chafa "$1"
  fi
  exiftool "$1"
elif [ "$category" = text ]; then
  bat --color=always "$1"
else
  lesspipe "$1" | bat --color=always
fi
# lesspipe.sh don't use eza, bat and chafa, it use ls and exiftool. so we create a lessfilter.
