""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" ~/.vim/vimrc
" Mark Spain
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


" Load extra plugins                                                   
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
execute pathogen#infect()                                              
execute pathogen#helptags()                                            


" vim options
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
filetype plugin on
set modelines=0		" prevent modelines (security)
set nocompatible	" use vim defaults instead of 100% vi compatibility
set showmode        " show the current mode
set history=700     " sets how many lines of history VIM has to remember
set cmdheight=2     " height of the command bar
set number          " turn on line numbers
set showmatch       " show matching brackets when text indicator is over them
set mat=2           " how many tenths of a second to blink when matching brackets
set mouse=a         " enable mouse interaction


" vim color options
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set t_Co=256                      " enable 256 color mode (needed for molokai)
set background=dark               " we like a dark background (easier on the eyes)
colorscheme molokai               " set the default color scheme to molokai
let g:solarized_termcolors=256    " required for solarized
"colorscheme solarized          " set the default color scheme to solarized

" set transparent background
hi Normal guibg=NONE ctermbg=NONE


" whitespace stuff
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set expandtab       " use spaces instead of tabs                                                               
set shiftwidth=2    " 1 tab == 4 spaces                                                                        
set tabstop=2       " 1 tab == 4 spaces                                                                        
set softtabstop=2   " 1 tab == 4 spaces
set showtabline=2   " always show tab line
set smartindent     " smart indent                                                                             
set wrap            " wrap lines                                                                               
"set nowrap          " don't wrap lines 


" search options
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set hlsearch        " hightlight search results
set incsearch       " incremental search
set ignorecase      " ignore case when searching
set smartcase       " when searching try to be smart about case


" set file types                                                                                
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""                         
" Thorfile, Rakefile, Vagrantfile and Gemfile are Ruby                                          
au BufRead,BufNewFile {Guardfile,Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru} set ft=ruby


" NERDTree settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
let NERDTreeDirArrows=0
let NERDTreeHighlightCursorline=1
let NERDTreeMouseMode=2
let NERDTreeWinSize=1
let NERDTreeChDirMode=2
let NERDTreeWinSize=27


" tab completion
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc

" yaml settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
set foldlevelstart=20

" json settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:vim_json_syntax_conceal = 0
let g:vim_json_syntax_concealcursor = 0

" indent settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:indentLine_concealcursor=""

" custom mappings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %

"
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

