"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$os\
$username\
[](bg:color_yellow fg:color_orange)\
$hostname\
[](fg:color_yellow bg:color_aqua)\
$directory\
[](fg:color_aqua bg:color_blue)\
$git_branch\
$git_status\
[](fg:color_blue bg:color_bg3)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

#right_format = "[](fg:color_bg1)$shell[](fg:color_bg1)"

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_sea = '#83a598'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[hostname]
ssh_only = false
style = "fg:color_fg0 bg:color_yellow"
format = '[ $hostname ]($style)'
trim_at = '.companyname.com'
disabled = false

[directory]
style = "fg:color_fg0 bg:color_aqua"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
format = '[ $symbol $branch ](fg:color_fg0 bg:color_blue)'

[git_status]
format = '[($all_status$ahead_behind )](fg:color_fg0 bg:color_blue)'

[nodejs]
symbol = ""
format = '[ $symbol( $version) ](fg:color_sea bg:color_bg3)'

[c]
symbol = " "
format = '[ $symbol( $version) ](fg:color_sea bg:color_bg3)'

[rust]
symbol = ""
format = '[ $symbol( $version) ](fg:color_sea bg:color_bg3)'

[golang]
symbol = ""
format = '[ $symbol( $version) ](fg:color_sea bg:color_bg3)'

[php]
symbol = ""
format = '[ $symbol( $version) ](fg:color_sea bg:color_bg3)'

[java]
symbol = " "
format = '[ $symbol( $version) ](fg:color_sea bg:color_bg3)'

[kotlin]
symbol = ""
format = '[ $symbol( $version) ](fg:color_sea bg:color_bg3)'

[haskell]
symbol = ""
format = '[ $symbol( $version) ](fg:color_sea bg:color_bg3)'

[python]
symbol = ""
format = '[ $symbol( $version) ](fg:color_sea bg:color_bg3)'

[time]
disabled = false
time_format = "%_I:%M:%S %p"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[shell]
disabled = true
style = "fg:color_fg0 bg:color_bg1"
format = '[ $indicator ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_aqua)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_aqua)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
