#!/bin/bash
# ----------------------------------------------------------------------
# ~/.dotfiles/scripts/bootstrap
# Mark Spain
# ----------------------------------------------------------------------

# install rvm
[[ ! -a $HOME/.rvm/bin/rvm ]] && curl -sSL https://get.rvm.io | bash -s stable --ruby --ignore-dotfiles

# install homebrew
[[ ! -a /usr/local/bin/brew ]] && ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# install homebrew casks in /Applications instead of ~/Applications
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# make sure everything is good to go with homebrew
brew doctor
brew update

# add homebrew support for brewfiles/caskfiles
if [[ -z $(gem list | grep "brewdler") ]]; then
  echo "Installing brewdler, need permission..."
  sudo gem install brewdler
fi

# install brew/cask packages
[[ -a ./Brewfile ]] && brewdler install

# cleanup
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

! [[ -a "$HOME/Developer" ]] && mkdir $HOME/Developer

./install.sh

