#!/bin/bash
# ----------------------------------------------------------------------
# ~/.dotfiles/scripts/Brewfile
# Mark Spain
# ----------------------------------------------------------------------

# tap the repos
brew tap caskroom/homebrew-cask
brew tap caskroom/fonts

# install brew packages
brew install bash-completion2
brew install brew-cask
brew install cowsay
brew install fortune
brew install neofetch
brew install node
brew install p7zip
brew install pianobar
brew install tree
brew install vim
brew install wget

# install fonts
brew cask install font-source-code-pro

# install casks
brew cask install adobe-air
brew cask install appcleaner
brew cask install arduino
brew cask install atom
brew cask install bartender
brew cask install coda
brew cask install codekit
brew cask install curse
brew cask install dropbox
brew cask install eclipse-ide
brew cask install flux
brew cask install firefox
brew cask install github-desktop
brew cask install google-chrome
brew cask install google-drive
brew cask install grandperspective
brew cask install imageoptim
brew cask install iterm2
brew cask install istat-menus
brew cask install java
brew cask install lastpass
brew cask install league-of-legends
brew cask install macgdbp
brew cask install gemini
brew cask install mamp
brew cask install music-manager
brew cask install onyx
brew cask install pandora-one
brew cask install vnc-viewer
brew cask install sizeup
brew cask install skype
brew cask install steam
brew cask install sublime-text
brew cask install teamviewer
brew cask install the-unarchiver
brew cask install transmission
brew cask install vlc
